import bornagain as ba
from bornagain import deg, nm

def get_sample():
    # Define materials
    material_D2O = ba.MaterialBySLD("D2O", 6.36e-06, 0.0)
    material_Organic_Material = ba.MaterialBySLD("Organic Material", 1e-06, 0.0)
    material_SiO2 = ba.MaterialBySLD("SiO2", 3.47e-06, 0.0)
    material_Silicon = ba.MaterialBySLD("Silicon", 2.07e-06, 0.0)

    # Define form factors
    ff = ba.Sphere(25*nm)

    # Define particles
    particle = ba.Particle(material_Organic_Material, ff)

    # Define 2D lattices
    lattice = ba.BasicLattice2D(
    50*nm, 50*nm, 120*deg, 0*deg)

    # Define interference functions
    iff = ba.Interference2DParacrystal(lattice, 0*nm, 20000*nm, 20000*nm)
    iff.setIntegrationOverXi(True)
    iff_pdf_1 = ba.Profile2DCauchy(1*nm, 1*nm, 0*deg)
    iff_pdf_2 = ba.Profile2DCauchy(1*nm, 1*nm, 0*deg)
    iff.setProbabilityDistributions(iff_pdf_1, iff_pdf_2)

    # Define particle layouts
    layout = ba.ParticleLayout()
    layout.addParticle(particle, 1.0)
    layout.setInterference(iff)
    layout.setTotalParticleSurfaceDensity(0.000461880215352)

    # Define roughness
    roughness_1 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_2 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_3 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_4 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_5 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_6 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_7 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_8 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_9 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_10 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_11 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_12 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_13 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_14 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_15 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_16 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_17 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_18 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_19 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_20 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_21 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_22 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_23 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_24 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_25 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_26 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_27 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_28 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_29 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_30 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_31 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_32 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_33 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_34 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_35 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_36 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_37 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_38 = ba.LayerRoughness(1.0, 0.3, 50*nm)
    roughness_39 = ba.LayerRoughness(1.0, 0.3, 50*nm)

    # Define layers
    layer_1 = ba.Layer(material_Silicon)
    layer_2 = ba.Layer(material_SiO2, 1*nm)
    layer_3 = ba.Layer(material_D2O, 5*nm)
    layer_4 = ba.Layer(material_Organic_Material, 5*nm)
    layer_5 = ba.Layer(material_D2O, 5*nm)
    layer_6 = ba.Layer(material_Organic_Material, 5*nm)
    layer_7 = ba.Layer(material_D2O, 5*nm)
    layer_8 = ba.Layer(material_Organic_Material, 5*nm)
    layer_9 = ba.Layer(material_D2O, 5*nm)
    layer_10 = ba.Layer(material_Organic_Material, 5*nm)
    layer_11 = ba.Layer(material_D2O, 5*nm)
    layer_12 = ba.Layer(material_Organic_Material, 5*nm)
    layer_13 = ba.Layer(material_D2O, 5*nm)
    layer_14 = ba.Layer(material_Organic_Material, 5*nm)
    layer_15 = ba.Layer(material_D2O, 5*nm)
    layer_16 = ba.Layer(material_Organic_Material, 5*nm)
    layer_17 = ba.Layer(material_D2O, 5*nm)
    layer_18 = ba.Layer(material_Organic_Material, 5*nm)
    layer_19 = ba.Layer(material_D2O, 5*nm)
    layer_20 = ba.Layer(material_Organic_Material, 5*nm)
    layer_21 = ba.Layer(material_D2O, 5*nm)
    layer_22 = ba.Layer(material_Organic_Material, 5*nm)
    layer_23 = ba.Layer(material_D2O, 5*nm)
    layer_24 = ba.Layer(material_Organic_Material, 5*nm)
    layer_25 = ba.Layer(material_D2O, 5*nm)
    layer_26 = ba.Layer(material_Organic_Material, 5*nm)
    layer_27 = ba.Layer(material_D2O, 5*nm)
    layer_28 = ba.Layer(material_Organic_Material, 5*nm)
    layer_29 = ba.Layer(material_D2O, 5*nm)
    layer_30 = ba.Layer(material_Organic_Material, 5*nm)
    layer_31 = ba.Layer(material_D2O, 5*nm)
    layer_32 = ba.Layer(material_Organic_Material, 5*nm)
    layer_33 = ba.Layer(material_D2O, 5*nm)
    layer_34 = ba.Layer(material_Organic_Material, 5*nm)
    layer_35 = ba.Layer(material_D2O, 5*nm)
    layer_36 = ba.Layer(material_Organic_Material, 5*nm)
    layer_37 = ba.Layer(material_D2O, 5*nm)
    layer_38 = ba.Layer(material_Organic_Material, 5*nm)
    layer_39 = ba.Layer(material_D2O, 50*nm)
    layer_40 = ba.Layer(material_D2O)
    layer_40.addLayout(layout)

    # Define sample
    sample = ba.MultiLayer()
    sample.addLayer(layer_1)
    sample.addLayerWithTopRoughness(layer_2, roughness_1)
    sample.addLayerWithTopRoughness(layer_3, roughness_2)
    sample.addLayerWithTopRoughness(layer_4, roughness_3)
    sample.addLayerWithTopRoughness(layer_5, roughness_4)
    sample.addLayerWithTopRoughness(layer_6, roughness_5)
    sample.addLayerWithTopRoughness(layer_7, roughness_6)
    sample.addLayerWithTopRoughness(layer_8, roughness_7)
    sample.addLayerWithTopRoughness(layer_9, roughness_8)
    sample.addLayerWithTopRoughness(layer_10, roughness_9)
    sample.addLayerWithTopRoughness(layer_11, roughness_10)
    sample.addLayerWithTopRoughness(layer_12, roughness_11)
    sample.addLayerWithTopRoughness(layer_13, roughness_12)
    sample.addLayerWithTopRoughness(layer_14, roughness_13)
    sample.addLayerWithTopRoughness(layer_15, roughness_14)
    sample.addLayerWithTopRoughness(layer_16, roughness_15)
    sample.addLayerWithTopRoughness(layer_17, roughness_16)
    sample.addLayerWithTopRoughness(layer_18, roughness_17)
    sample.addLayerWithTopRoughness(layer_19, roughness_18)
    sample.addLayerWithTopRoughness(layer_20, roughness_19)
    sample.addLayerWithTopRoughness(layer_21, roughness_20)
    sample.addLayerWithTopRoughness(layer_22, roughness_21)
    sample.addLayerWithTopRoughness(layer_23, roughness_22)
    sample.addLayerWithTopRoughness(layer_24, roughness_23)
    sample.addLayerWithTopRoughness(layer_25, roughness_24)
    sample.addLayerWithTopRoughness(layer_26, roughness_25)
    sample.addLayerWithTopRoughness(layer_27, roughness_26)
    sample.addLayerWithTopRoughness(layer_28, roughness_27)
    sample.addLayerWithTopRoughness(layer_29, roughness_28)
    sample.addLayerWithTopRoughness(layer_30, roughness_29)
    sample.addLayerWithTopRoughness(layer_31, roughness_30)
    sample.addLayerWithTopRoughness(layer_32, roughness_31)
    sample.addLayerWithTopRoughness(layer_33, roughness_32)
    sample.addLayerWithTopRoughness(layer_34, roughness_33)
    sample.addLayerWithTopRoughness(layer_35, roughness_34)
    sample.addLayerWithTopRoughness(layer_36, roughness_35)
    sample.addLayerWithTopRoughness(layer_37, roughness_36)
    sample.addLayerWithTopRoughness(layer_38, roughness_37)
    sample.addLayerWithTopRoughness(layer_39, roughness_38)
    sample.addLayerWithTopRoughness(layer_40, roughness_39)

    return sample